### ISSUE TITLE
Python 3 jack.UsageError

### ISSUE THREAD

**Issue by hpfmn** [umlaeute/pyjack#1]
Hey,
I tried to use pyjack with Python 3.3, Numpy 1.8, Scipy 0.13.1. But I always get "jack.UsageError: A connection is already established." when calling jack.attach() for the very first time.

I also looked a little into the code and when I comment the line:
452     if(client->pjc != NULL) {
453         PyErr_SetString(JackUsageError, "A connection is already established.");
454         return NULL;
455     }

I'm just getting a segmentation fault. (I mean this makes sense since for some reason there is data behind client...) Maybe you have an idea at what I can look to fix this?

Best regards,
Johannes

**Comment by umlaeute** [comment]
could you provide a minimal example, that triggers the problem?

**Comment by hpfmn** [comment]
Yes:

import jack
import time

jack.attach('test')

executing:

$ python3 trigger.py
Traceback (most recent call last):
   File "trigger.py", line 4, in <module>
     jack.attach('test')
jack.UsageError: A connection is already established.

Greetings,
Johannes

Am 03.12.2013 18:58, schrieb umläute:

> could you provide a minimal example, that triggers the problem?
